### ISSUE TITLE
Register method error

### ISSUE THREAD

**Issue by Bigbhardwaj** [cornflourblue/aspnet-core-registration-login-api#1]
When i try to hit register got error as below
 
![image](https://user-images.githubusercontent.com/9026778/46684179-b2bb5f80-cc0f-11e8-8aa9-bb7aa3af33e1.png)

**Comment by cornflourblue** [comment]
the body should be json data, change the "form-data" radio button to "raw" and select "JSON (application/json)", then enter the username and password as a json object in the body field.

**Comment by Bigbhardwaj** [comment]
Yes I figured it out soon..I Checked register method with below code and Postaman returns with success.
public IActionResult Register([FromForm]UserDto userDto)
        {
            // map dto to entity
            var user = _mapper.Map<User>(userDto);
            return Ok(new
            {
               user
            });
 but if exact code is in place in Register method. then the execution flow hit by another blocker. 
Postman request 

![image](https://user-images.githubusercontent.com/9026778/46712501-001ae980-cc6f-11e8-93c0-9e9318c6bb84.png)

Exception 

![image](https://user-images.githubusercontent.com/9026778/46712416-a87c7e00-cc6e-11e8-83a2-6037fa616a70.png)
